apps/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('users/', views.users, name='users'),	
    path('users/add', views.add_user, name='addUser'),
    path('users/delete/<id>', views.delete_user, name='deleteUser'),
    path('users/edit/<id>', views.edit_user, name='editUser'),
    path('inventory/', views.inventory, name='inventory'),
	path('inventory/add', views.add_inventory, name='addInventory'),
	path('inventory/delete/<id>', views.delete_inventory, name='deleteInventory'),
	path('inventory/edit/<id>', views.edit_inventory, name='editInventory'),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
    url(r'^accounts/login/$', 
        auth_views.LoginView.as_view(template_name="authenticate/login.html"), 
        name='login'),
    url(r'^accounts/profile/$', 
        auth_views.LoginView.as_view(template_name="authenticate/home.html"), 
        name='home'),
    # path('', TemplateView.as_view(template_name='authenticate/home.html'), name='home')
]

apps/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
import json

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ID = models.AutoField(primary_key=True)
    roles = (
        ('user', 'USER'),
        ('admin', 'ADMIN'),
        ('auditor', 'AUDITOR'),
        ('manager', 'MANAGER')
    )
    role = models.CharField(choices=roles,max_length=7,default='user')
    departments = (
        ('CA','Clothing and Apparel'),
        ('HD','Home and Decors'),
        ('CS','Construction Supplies')
        )
    department = models.CharField(max_length=2,choices=departments,default='CA')

    @classmethod
    def createProfile(self, data):
        exists = User.objects.filter(username=data.get("username","")).exists()
        if not exists:
            user = User(first_name=data.get("fname",""), 
                last_name=data.get("lname",""),
                username=data.get("username",""),
                email=data.get("email",""),
                is_active=True
                )
            if data.get("role","user") == 'admin':
                user.is_superuser=True
            if data.get("role","user") == 'manager':
                user.is_staff=True
            user.set_password(data.get("password",""))
            user.save()
            user.profile.role=data.get("role","user")
            user.profile.department=data.get("department","CA")
            user.save()

    #edit user, still not working, currently testing
    @classmethod
    def editUser (self, data):
        eUser=self.objects.get(pk=id)

        eUser.first_name=data.get("fname", "")
        eUser.last_name=data.get("lname", "")
        eUser.email=data.get("email", "")

        if data.get("role","user") == 'admin':
            user.is_superuser=True

        if data.get("role","user") == 'manager':
            user.is_staff=True

        eUser.profile.rold=data.get("role","")
        eUser.profile.department=data.get("department","")
        eUser.save()

        # exists = User.objects.filter(username=data.get("username","")).exists()
        # if exists:
        #     user = User(first_name=data.get("fname",""), 
        #         last_name=data.get("lname",""),
        #         email=data.get("email",""),
        #         )
        #     if data.get("role","user") == 'admin':
        #         user.is_superuser=True
        #     if data.get("role","user") == 'manager':
        #         user.is_staff=True
        #     user.save()
        #     user.profile.role=data.get("role","user")
        #     user.profile.department=data.get("department","CA")
        #     user.save()


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Product(models.Model):
    ID = models.AutoField(primary_key=True)
    SKU = models.CharField(max_length=11,null=True)
    name = models.CharField(max_length=50,null=True)
    price = models.IntegerField(default=0)
    departments = (
        ('CA','Clothing and Apparel'),
        ('HD','Home and Decors'),
        ('CS','Construction Supplies')
        )
    department = models.CharField(max_length=2,choices=departments,default='CA')
    stocks = models.IntegerField(default=0)
    sales = models.IntegerField(default=0)

class Inventory(models.Model):
    ID = models.AutoField(primary_key=True)
    products = models.TextField(null=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.DO_NOTHING)
    status_list = (
        ('DRAFT','Draft'),
        ('REJECTED','Rejected'),
        ('TO_AUDIT','To_Audit'),
        ('TO_APPROVE','To_Approve'),
        ('APPROVED','Approved')
    )
    status = models.CharField(max_length=10,choices=status_list, default='DRAFT')
    rejects = (
        ('AUDIT', 'AUDIT'),
        ('APPROVAL','APPROVAL'),
    )
    rejected_at = models.CharField(max_length=8,choices=rejects,null=True)
    departments = (
        ('CA','Clothing and Apparel'),
        ('HD','Home and Decors'),
        ('CS','Construction Supplies')
        )
    department = models.CharField(max_length=2,choices=departments,default='CA')
    week = models.CharField(max_length=10,null=True)


    @classmethod
    def createInventory(self,user,department,data):
        products = Product.objects.filter(department=department)
        product_inventory = {}
        for product in products:
            if not str(product.ID)+'_stocks' and not str(product.ID)+'_sales' in data:
                continue
            if product.ID not in product_inventory: 
                product_inventory[product.ID] = {}
            inv_stocks = data.get(str(product.ID)+'_stocks',0)
            inv_sales = data.get(str(product.ID)+'_sales',0)
            product_inventory[product.ID]['ID'] = product.ID
            product_inventory[product.ID]['name'] = product.name
            product_inventory[product.ID]['SKU'] = product.SKU
            product_inventory[product.ID]['old_stocks'] = product.stocks
            product_inventory[product.ID]['old_sales'] = product.sales
            product_inventory[product.ID]['inv_stocks'] = inv_stocks
            product_inventory[product.ID]['inv_sales'] = inv_sales

        inventory = self(created_by=user,
                    products=json.dumps(product_inventory),
                    department=department,
                    week=data.get("week_year",""))
        if data.get("draft","") != "":
            inventory.status = 'DRAFT'
        elif data.get("to_audit","") != "":
            inventory.status = 'TO_AUDIT'
        inventory.save()

    @classmethod
    def editInventory(self,id,user,department,data):
        products = Product.objects.filter(department=department)
        product_inventory = {}
        for product in products:
            if not str(product.ID)+'_stocks' and not str(product.ID)+'_sales' in data:
                continue
            if product.ID not in product_inventory: 
                product_inventory[product.ID] = {}
            inv_stocks = data.get(str(product.ID)+'_stocks',0)
            inv_sales = data.get(str(product.ID)+'_sales',0)
            product_inventory[product.ID]['ID'] = product.ID
            product_inventory[product.ID]['name'] = product.name
            product_inventory[product.ID]['SKU'] = product.SKU
            product_inventory[product.ID]['old_stocks'] = product.stocks
            product_inventory[product.ID]['old_sales'] = product.sales
            product_inventory[product.ID]['inv_stocks'] = inv_stocks
            product_inventory[product.ID]['inv_sales'] = inv_sales
        inventory = self.objects.get(pk=id)
        inventory.products=json.dumps(product_inventory)
        inventory.week=data.get("week_year","")
        if data.get("draft","") != "":
            inventory.status = 'DRAFT'
        elif data.get("to_audit","") != "":
            inventory.status = 'TO_AUDIT'
        elif data.get("to_approve","") != "":
            inventory.status = 'TO_APPROVE'
        elif data.get("approve","") != "":
            inventory.status = 'APPROVED'
        elif data.get("reject","") != "":
            inventory.status = 'REJECTED'
        inventory.save()

apps/templates/authenticate/addinventory.html
{% extends 'authenticate/base.html' %}

{% block content %}

<div class="col-md-6 offset-md-3">    
    <h2 class="form-signin-heading">Please Add Inventory</h2>
    <form action={% url 'addInventory' %} class="form-signin" method="POST">
        {% csrf_token %}
        
        <div class="form-group">
            {% comment %} <input type="week" name="week_year" class="form-control" placeholder="Week"> {% endcomment %}
            <input type="week" name="week_year" class="form-control center-block" placeholder="Week">
        </div>

        <div class="form-group">
            <label for="role">Select Department</label>
            <select class="form-control input-lg" id="department" name="department"> 
                <option value="CA">Clothing and Apparel</option>
                <option value="HD">Home and Decors</option>
                <option value="CS">Construction Supplies</option>
                {% comment %} {% for alldepartments in departments %}
                    <option value="{{ alldepartments.department }}">{{ alldepartments.get_department_display }}</option>
                {% endfor %} {% endcomment %}
            </select>
        </div>

        <div class="form-group">
            <label for="role">Select Role</label>
            <select class="form-control input-lg" id="role" name="role"> 
                <option value="user">USER</option>
                <option value="auditor">AUDITOR</option>
                <option value="manager">MANAGER</option>
                <option value="admin">ADMIN</option> 
            </select>
         </div>

        {% if products %}
            Products
            <div class="container-fluid">
            <table align="center" class="table table-bordered table-hover">
                <tr>
                    <th>Name</th>
                    <th>SKU</th>
                    <th colspan="2">Stocks</th>
                    <th colspan="2">Sales</th>
                </tr>
                {% for product in products %}
                    <tr class="itemlist">
                        <td>{{ product.name }}</td>
                        <td>{{ product.SKU }}</td>
                        <td>{{ product.stocks }}</td>
                        <td><input type="number" name="{{product.ID }}_stocks" /></td>
                        <td>{{ product.sales }}</td>
                        <td><input type="number" name="{{product.ID }}_sales" /></td>
                    </tr>
                {% endfor %}
            </table>
            </div>
        

            {% csrf_token %}
            <input type="submit" name="draft" value="Save"/>
            {% csrf_token %}
            <input type="submit" name="to_audit" value="Submit"/>        
        {% endif %}

        {% comment %} <button class="btn btn-lg btn-primary btn-block" type="submit">Save</button> {% endcomment %}

    </form>
</div> 



{% endblock %}

apps/templates/authenticate/adduser.html
{% extends 'authenticate/base.html' %}

{% block content %}

<div class="col-md-6 offset-md-3">
    <h2 class="form-signin-heading">Please Add user</h2>
      <form action={% url 'addUser' %} class="form-signin" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" name="fname" class="form-control" placeholder="First Name" required autofocus>
        </div>

        <div class="form-group">
            <input type="text" name="lname" class="form-control" placeholder="Last Name" required>
        </div>

        <div class="form-group">
            <input type="email" name="email" class="form-control" placeholder="Email" required>
        </div>

        <div class="form-group">
            <input type="text" name="username" class="form-control" placeholder="Username" required>
        </div>

        <div class="form-group">
            <input type="password" name="password" class="form-control" placeholder="Password" required>
        </div>

        <div class="form-group">
            <input type="password" name="cpassword" class="form-control" placeholder="Confirm Password" required>
        </div>

        <div class="form-group">
            <label for="role">Select Role</label>
            <select class="form-control input-lg" id="role" name="role"> 
                <option value="user">USER</option>
                <option value="auditor">AUDITOR</option>
                <option value="manager">MANAGER</option>
                <option value="admin">ADMIN</option> 
            </select>
            
            {% comment %}             
                <tr>
                <td>Role</td>
                <td>
                    <select id="role" name="role">
                        <option value="user">USER</option>
                        <option value="auditor">AUDITOR</option>
                        <option value="manager">MANAGER</option>
                        <option value="admin">ADMIN</option>
                    </select>
                </td>
                </tr>
            {% endcomment %}
        </div>

        <div class="form-group">

            <label for="role">Select Department</label>
            <select class="form-control input-lg" id="department" name="department"> 
                <option value="CA">Clothing and Apparel</option>
                <option value="HD">Home and Decors</option>
                <option value="CS">Construction Supplies</option>
            </select>


            {% comment %} 
                <tr>
                <td>Department</td>
                <td>
                    <select id="department" name="department">
                        <option value="CA">Clothing and Apparel</option>
                        <option value="HD">Home and Decors</option>
                        <option value="CS">Construction Supplies</option>
                    </select>
                </td>
                </tr>
            {% endcomment %}
        </div>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Save</button>
      </form>
    </div> 



{% endblock %}

apps/templates/authenticate/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% comment %} <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> {% endcomment %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS  -->
    {% comment %} {% load static %}
    <link rel="stylesheet" href="{% static "dist/css/bootstrap.min.css" %}"> {% endcomment %}
    {% comment %} <link rel="stylesheet" href="{% static "dist/css/bootstrap.min.css" %}"> {% endcomment %}
    
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static "favicon.ico" %}"/>  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>    
    <!-- 
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">    
         -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">     
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-toggle">
            <a class="navbar-brand" href="{% url 'home' %}"><strong>CPE Mechandize Company</strong></a>
        </div>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"</span>
        </button>
       <!-- -->
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="navbar-text"><em><small>{ {{ user.username }} || {{ user.profile.get_department_display }} || {{ user.profile.get_role_display }} } </small></em></li>
                            
                            <li class="nav-item"><a class="nav-link" href="{% url 'users' %}">Users</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'addUser' %}">Add User</a></li>
                        
                            <li class="nav-item"><a class="nav-link" href="{% url 'inventory' %}">Inventory</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'addInventory' %}">Add Inventory</a></li>                        
                       
{% comment %} 
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                    User
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu bg-dark" aria-labelledby="dropdownMenu1">
                                    <li class="nav-item"><a class="nav-link" href="{% url 'users' %}">All Users</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'addUser' %}">Add User</a></li>
                                </ul>
                            </div>

                            <div class="dropdown">
                                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                    Inventory
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu bg-dark" aria-labelledby="dropdownMenu2">
                                    <li class="nav-item"><a class="nav-link" href="{% url 'inventory' %}">All Inventories</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'addInventory' %}">Add Inventory</a></li>                        
                                </ul>
                            </div>
 {% endcomment %}


                        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
    </nav>
    
    <div class="container-fluid">    
        <br>
        
        {% if messages %} 
            {% for message in messages %}
                <div class="container alert alert-warning alert-dismissable" role="alert">
                    <button class="close" data-dismiss="alert">
                        <small><sup>x</sup></small>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        
        {% endif %}

        {% block content %}
        {% endblock %}

    </div>

    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    

    {% comment %} <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static "js/jquery3.js" %}></script>
    <script src="{% static "js/popper.js" %}></script>
    <script src="{% static "dist/js/bootstrap.min.js" %}></script>
    <script src="{% static "js/holder.min.js" %}></script> {% endcomment %}
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>   
  </body>
</html>

apps/templates/authenticate/editinventory.html
{% extends 'authenticate/base.html' %}

{% block content %}

<div class="col-md-6 offset-md-3">    
    <h2 class="form-signin-heading">Edit Inventory</h2>
    <form action="/authenticate/inventory/edit/{{ inventory.ID }}" class="form-signin" method="POST">
        {% csrf_token %}
        
        <div class="form-group">
            {% comment %} <input type="week" name="week_year" class="form-control" placeholder="Week"> {% endcomment %}
            <input type="week" name="week_year" class="form-control center-block" placeholder="Week">
        </div>        

        {% if products %}
            Products
            <div class="container-fluid">
            <table align="center" class="table table-bordered table-hover">
                <tr>
                    <th>Name</th>
                    <th>SKU</th>
                    <th colspan="2">Stocks</th>
                    <th colspan="2">Sales</th>
                </tr>
                {% for product in products %}
                    <tr class="itemlist">
                        <td>{{ product.name }}</td>
                        <td>{{ product.SKU }}</td>
                        <td>{{ product.old_stocks }}</td>
                        <td><input type="number" name="{{product.ID }}_stocks" value="{{ product.inv_stocks }}" /></td>
                        <td>{{ product.sales }}</td>
                        <td><input type="number" name="{{product.ID }}_sales" value="{{ product.inv_sales }}" /></td>
                    </tr>
                {% endfor %}
            </table>
            </div>
        {% endif %}

    {% if user.profile.role == "user" %}
		{% csrf_token %}
		<input type="submit" name="draft" value="Save"/>
		
        {% csrf_token %}
		<input type="submit" name="to_audit" value="Submit for Audit"/>
	
    {% elif user.profile.role == "auditor" %}
        {% csrf_token %}	
        <input type="submit" name="reject" value="Reject"/>
		
        {% csrf_token %}
		<input type="submit" name="to_approve" value="Submit for Approval"/>
	
    {% elif user.profile.role == "manager" %}
		{% csrf_token %}
		
        <input type="submit" name="reject" value="Reject"/>
		{% csrf_token %}
		<input type="submit" name="approve" value="Submit"/>

	{% endif %}        

    </form>
</div> 

{% endblock %}

apps/templates/authenticate/edituser.html
{% extends 'authenticate/base.html' %}

{% block content %}

<div class="col-md-6 offset-md-3">
    <h2 class="form-signin-heading">Editing username <strong><em>{{ users.username }}</em></strong> </h2>
      <form action={% url 'editUser' users.pk %} class="form-signin" method="POST">
        {% csrf_token %}

        <div class="form-group">
            <input type="hidden" name="username" class="form-control" value="{{ users.username }}">
        </div>


        <div class="form-group">
            <label for="fname">First Name</label>
            <input type="text" name="fname" class="form-control" value="{{ users.first_name }}" required>
        </div>

        <div class="form-group">
            <label for="lname">Last Name</label>
            <input type="text" name="lname" class="form-control" value="{{ users.last_name }}" required>
        </div>

        <div class="form-group">
            <label for="email">Email Address</label>
            <input type="email" name="email" class="form-control" value="{{ users.email }}" required>
        </div>

        <div class="form-group">
            <label for="crole"><strong>Current</strong> Role</label>
            <input type="text" name="crole" class="form-control" value="{{ users.profile.get_role_display }}" disabled>
        </div>
        <div class="form-group">
            <label for="role">Select <strong>New</strong> Role</label>
            <select class="form-control input-lg" id="role" name="role"> 
                <option value="user">USER</option>
                <option value="auditor">AUDITOR</option>
                <option value="manager">MANAGER</option>
                <option value="admin">ADMIN</option> 
            </select>                        
        </div>

        <div class="form-group">
            <label for="cdept"><b>Current</b> Department</label>
            <input value="{{ users.profile.get_department_display }}" type="text" name="cdept" class="form-control" disabled>
        </div>

        <div class="form-group">

            <label for="role">Select <b>New</b> Department</label>
            <select class="form-control input-lg" id="department" name="department"> 
                <option value="CA">Clothing and Apparel</option>
                <option value="HD">Home and Decors</option>
                <option value="CS">Construction Supplies</option>
            </select>            
        </div>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
      </form>
    </div> 



{% endblock %}

apps/templates/authenticate/home.html
{% extends 'authenticate/base.html' %}



{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static "/dist/css/carousel.css" %}">



<div class="container-fluid carousel slide" role="listbox">
    <div class="item active">
        {% comment %} <img class="media-object"  width="100%" height="70%" src="{% static "/img/123.jpg" %}" alt="First slide">
        <div class="container">
            <div class="carousel-caption">
              <h1>Year end Sale!!!</h1>
              <p>70% Off on all items starting 15 Dec.</p>
            </div>
        </div> {% endcomment %}

        <img class="media-object"  width="100%" height="70%" src="{% static "/img/124.jpg" %}" alt="First slide">
        <div class="container">
            <div class="carousel-caption">
              <h1>Ang Probinsyano!!!</h1>
              <p>MMFF oficial entry.</p>
            </div>
        </div>
    </div>
</div>


{% endblock %}

apps/templates/authenticate/inventory.html
{% extends 'authenticate/base.html' %}

{% block content %}


<h2 class="form-signin-heading">Inventory List</h2>

<table align="center" class="table table-bordered table-hover">
	<tr>
		<th>Department</th>
		<th>Week</th>
		<th>Author</th>
		<th>Status</th>
		<th colspan="2"></th>
	</tr>
	{% if inventories %}
    {% for inventory in inventories %}
    <tr class="itemlist">
    	<td>{{ inventory.department }}</a></td>
    	<td>{{ inventory.week }}</a></td>
    	<td>{{ inventory.created_by.username }}</a></td>
    	<td>{{ inventory.status }}</td>
    	<td>
    		<form action="{% url 'deleteInventory' inventory.ID %}" method="POST">{% csrf_token %}
    			<input type="submit" class="deluser" value="Delete"/>
			</form>
		</td>
		<td>
			<form action="{% url 'editInventory' inventory.ID %}" method="GET">{% csrf_token %}
    			<input type="submit" value="Edit"/>
			</form>
		</td>
	</tr>
    {% endfor %}
	{% else %}
    <tr>
    	<td colspan="7">No inventories available.</td>
    </tr>
    {% endif %}	
</table>



<form action={% url 'addInventory' %} class="form-signin" method="GET">
        {% csrf_token %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Add Item
        </button>
</form>


{% endblock %}

apps/templates/authenticate/login.html
{% extends 'authenticate/base.html' %}

{% block content %}
    
    
    <div class="col-md-6 offset-md-3">
    <h2 class="form-signin-heading">Please sign in</h2>
      <form class="form-signin" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" name="username" class="form-control" placeholder="Enter Username" required autofocus>
        </div>

        <div class="form-group">
            <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" name="password" class="form-control" placeholder="Password" required>
        </div>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>
    </div> 
    
    
{% endblock %}

apps/templates/authenticate/users.html
{% extends 'authenticate/base.html' %}

{% block content %}


<h2 class="form-signin-heading">List of Users</h2>

<table align="center" class="table table-bordered table-hover">
	<tr>
        <th>First Name</th>
		<th>Last Name</th>
		<th>Username</th>
		<th>Role</th>
		<th>Department</th>
		<th colspan="2"></th>
	</tr>
	{% if users %}
    {% for user in users %}
    <tr>
        <td>{{ user.first_name }}</a></td>
    	<td>{{ user.last_name }}</a></td>
    	<td>{{ user.username }}</a></td>
    	<td>{{ user.profile.get_role_display }}</td>
    	<td>{{ user.profile.get_department_display }}</td>
    	<td>
    		{% comment %}  <form action={% url 'deleteUser' user.ID  %}  method="POST">{% csrf_token %} {% endcomment %}
            <form action="/users/delete/{{user.pk}}"  method="POST">{% csrf_token %}
    			<input type="submit" class="deluser" value="Delete"/>

                {% comment %} <button type="button" class="btn btn-default btn-lg" type="submit" class="deluser" value="Delete">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete
                </button> {% endcomment %}
			</form>
		</td>
		<td>
			<form action="/users/edit/{{user.pk}}" method="GET">{% csrf_token %}
    			<input type="submit" value="Edit"/>
                
                {% comment %} <button type="button" class="btn btn-default btn-lg" type="submit" value="Edit">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
                </button> {% endcomment %}
			</form>
		</td>
	</tr>
    {% endfor %}
	{% else %}
    <tr>
    	<td colspan="7">No registered users.</td>
    </tr>
    {% endif %}	
</table>



<form action={% url 'addUser' %} class="form-signin" method="GET">
        {% csrf_token %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Add User
        </button>
</form>


{% endblock %}